// NP ARRAYS

Numpy (ND arrrays) N- dimensional functions to develop calculations and mathematical operations with arrays in an efficient manner. (vectorization)
Operations of linear algebra , generation of random numbers amongst other fonctionalities of scientific computation.

In [48]:
import numpy as np

In [49]:
python_list= [1,2,3,4,5,6,7]
array=np.array(python_list)
print(array)

[1 2 3 4 5 6 7]


In [50]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
np.zeros((10,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
np.ones((10,2),int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [53]:
random_generator=np.random.default_rng()

In [54]:
print(random_generator)

Generator(PCG64)


In [55]:
random_generator.normal()


-0.019821749147781346

In [56]:
randin= random_generator.normal(loc=0,scale=1,size=12)
print(randin)

[-0.69818733 -0.28812299  0.51559298  0.39091047  1.41771664  0.78067162
  1.00296171  0.73486071  0.47037927 -1.16139821 -1.92664834  0.74761871]


In [57]:
randin100= random_generator.normal(loc=0,scale=1,size=100)


In [58]:
randin[::2]


array([-0.69818733,  0.51559298,  1.41771664,  1.00296171,  0.47037927,
       -1.92664834])

In [59]:
print(randin100)

[ 1.58191963  1.53908105  0.51964683  0.04777799  0.7010707   0.7764027
 -0.06532868  0.15647886 -0.5677341  -1.2158461  -0.27082314 -0.79762807
 -0.93100637  2.47070291 -0.5498342  -0.23941796  0.60255169 -0.61340954
 -0.75262327  0.96697644  0.02413327 -0.35714113 -0.36277311  0.2720207
  0.32328561 -0.23769368  0.86651038  0.98470923 -0.21676774  1.28115853
  0.14939904  0.25944404  0.45430563  0.96887439  0.38051635  0.68051807
 -1.06057568  0.45513967 -0.56500804 -0.64703469  0.26104074  1.18378519
  1.26255073 -0.3632434   1.18017245 -0.04191974  1.077482    0.30611327
  0.41662241  1.39352803  1.40867877 -0.26515764 -0.62090314  1.00329585
  0.09464496  0.38959232  2.07406218 -1.22568727 -0.69197932  0.04190615
  0.36803017 -0.4877923   0.64015426  0.00488723 -0.14590424  1.17008378
  1.42063077 -0.9674456   0.11962922 -0.13035259  2.68181694 -1.13790497
 -1.52988524  0.5449083  -0.31801982  1.533904   -0.62082836  0.78537262
  0.22416953  0.45916565 -0.32226703 -0.93398893 -0.5

In [60]:
randin100[::2]

array([ 1.58191963,  0.51964683,  0.7010707 , -0.06532868, -0.5677341 ,
       -0.27082314, -0.93100637, -0.5498342 ,  0.60255169, -0.75262327,
        0.02413327, -0.36277311,  0.32328561,  0.86651038, -0.21676774,
        0.14939904,  0.45430563,  0.38051635, -1.06057568, -0.56500804,
        0.26104074,  1.26255073,  1.18017245,  1.077482  ,  0.41662241,
        1.40867877, -0.62090314,  0.09464496,  2.07406218, -0.69197932,
        0.36803017,  0.64015426, -0.14590424,  1.42063077,  0.11962922,
        2.68181694, -1.52988524, -0.31801982, -0.62082836,  0.22416953,
       -0.32226703, -0.58305896,  1.69110765, -0.01607834, -1.53724999,
       -2.43641811,  0.38468906, -0.09903365,  0.32889629,  0.27968004])

In [61]:
randin100[1::2]

array([ 1.53908105,  0.04777799,  0.7764027 ,  0.15647886, -1.2158461 ,
       -0.79762807,  2.47070291, -0.23941796, -0.61340954,  0.96697644,
       -0.35714113,  0.2720207 , -0.23769368,  0.98470923,  1.28115853,
        0.25944404,  0.96887439,  0.68051807,  0.45513967, -0.64703469,
        1.18378519, -0.3632434 , -0.04191974,  0.30611327,  1.39352803,
       -0.26515764,  1.00329585,  0.38959232, -1.22568727,  0.04190615,
       -0.4877923 ,  0.00488723,  1.17008378, -0.9674456 , -0.13035259,
       -1.13790497,  0.5449083 ,  1.533904  ,  0.78537262,  0.45916565,
       -0.93398893,  0.47647144, -0.03195173,  0.50464524, -0.42672746,
       -0.08188048,  0.92004082, -0.04806951,  0.36557809,  1.19565278])

In [62]:
randin100[0:4]

array([1.58191963, 1.53908105, 0.51964683, 0.04777799])

In [63]:
list_randin = [0,50,99]
randin100[list_randin]

array([1.58191963, 1.40867877, 1.19565278])

In [64]:
random_generator_seed =np.random.default_rng(234444)

In [65]:
low=0
high=10
size=(3,4)
two_d_array=random_generator_seed.uniform(low,high,size)
two_d_array

array([[6.31642888, 8.88428445, 2.32222016, 8.29015815],
       [6.2049529 , 4.45305267, 3.98661712, 6.51275693],
       [4.02671536, 5.7290404 , 9.1184929 , 4.18738454]])

In [66]:
two_d_array[1,:]

array([6.2049529 , 4.45305267, 3.98661712, 6.51275693])

In [67]:
two_d_array[1:2,:]

array([[6.2049529 , 4.45305267, 3.98661712, 6.51275693]])

In [68]:
mask_5 = two_d_array > 5 
mask_5

array([[ True,  True, False,  True],
       [ True, False, False,  True],
       [False,  True,  True, False]])

In [69]:
two_d_array[mask_5]

array([6.31642888, 8.88428445, 8.29015815, 6.2049529 , 6.51275693,
       5.7290404 , 9.1184929 ])

In [70]:
a=np.array([0,2,5])
b=np.array([5,5,3])
a+b

array([5, 7, 8])

In [71]:
a=np.array([0,1,2])
b=5
a+b

array([5, 6, 7])

In [72]:
a=np.ones((3,3))
b=np.array([0,1,2])
a+b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [73]:
a=np.array([[0],[1],[2]])

In [74]:
a

array([[0],
       [1],
       [2]])

In [75]:
print(a.shape)

(3, 1)


In [76]:
b=np.array([1,2,3])
print(b.shape)

(3,)


In [77]:
a+b

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])