// NP ARRAYS

Numpy (ND arrrays) N- dimensional functions to develop calculations and mathematical operations with arrays in an efficient manner. (vectorization)
Operations of linear algebra , generation of random numbers amongst other fonctionalities of scientific computation.

In [2]:
import numpy as np

In [3]:
python_list= [1,2,3,4,5,6,7]
array=np.array(python_list)
print(array)

[1 2 3 4 5 6 7]


In [4]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros((10,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
np.ones((10,2),int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [11]:
random_generator=np.random.default_rng()

In [12]:
print(random_generator)

Generator(PCG64)


In [ ]:
random_generator.normal()


-0.7324403944189068

In [20]:
randin= random_generator.normal(loc=0,scale=1,size=12)
print(randin)

[-0.66841629 -0.11531623  0.45199332  0.44509553 -1.50907775  0.08803054
 -1.27852314  0.89539567 -0.35141261 -0.25050862 -0.82568998 -0.29844911]


In [23]:
randin100= random_generator.normal(loc=0,scale=1,size=100)


In [21]:
randin[::2]


array([-0.66841629,  0.45199332, -1.50907775, -1.27852314, -0.35141261,
       -0.82568998])

In [24]:
print(randin100)

[ 1.05081754  1.25116587 -0.3078189  -0.96681633  0.38116346  0.58812619
 -0.46748668  0.79152805 -0.33521527 -1.16869654 -0.0197416   0.54796616
  1.32793145 -0.14304202 -0.02107236  1.41220435  0.42608642 -2.24627248
 -0.72539213 -0.94229159  0.22671897 -0.11978039  0.14074481 -0.65518954
 -1.00388804 -1.42955666 -0.99815637 -0.08995155 -1.91429167  1.09165709
  0.34833294 -0.38214811  0.586396    0.4765948   0.99346613  1.167762
 -1.11442708  0.40171511  2.46306847  1.79704486  0.25297373 -0.20377387
  1.04016375 -0.4239768   0.83287448 -0.05372471 -0.3270871  -0.71830808
 -1.1014524   0.04328684  1.0316474   1.04740167  0.82565531  0.76167574
 -2.49627389  0.44500297  0.43940222 -0.82283116  1.05407116  1.81169297
  1.16964612 -0.28752125 -0.44758475  0.97017685 -0.96593631  0.73956995
  0.11272292 -0.73630442 -0.11651301  0.08692948 -1.38794081  0.13787149
  0.36717361  0.55253045 -2.26358028  0.06647032  1.0494234   2.3039466
  0.06543151  0.847597    0.05507558 -1.24881181 -1.64

In [25]:
randin100[::2]

array([ 1.05081754, -0.3078189 ,  0.38116346, -0.46748668, -0.33521527,
       -0.0197416 ,  1.32793145, -0.02107236,  0.42608642, -0.72539213,
        0.22671897,  0.14074481, -1.00388804, -0.99815637, -1.91429167,
        0.34833294,  0.586396  ,  0.99346613, -1.11442708,  2.46306847,
        0.25297373,  1.04016375,  0.83287448, -0.3270871 , -1.1014524 ,
        1.0316474 ,  0.82565531, -2.49627389,  0.43940222,  1.05407116,
        1.16964612, -0.44758475, -0.96593631,  0.11272292, -0.11651301,
       -1.38794081,  0.36717361, -2.26358028,  1.0494234 ,  0.06543151,
        0.05507558, -1.64148591,  0.7372947 , -2.01095408,  0.50647092,
       -0.51464149, -1.60967378,  0.35799207, -0.10965716, -0.01469994])

In [26]:
randin100[1::2]

array([ 1.25116587, -0.96681633,  0.58812619,  0.79152805, -1.16869654,
        0.54796616, -0.14304202,  1.41220435, -2.24627248, -0.94229159,
       -0.11978039, -0.65518954, -1.42955666, -0.08995155,  1.09165709,
       -0.38214811,  0.4765948 ,  1.167762  ,  0.40171511,  1.79704486,
       -0.20377387, -0.4239768 , -0.05372471, -0.71830808,  0.04328684,
        1.04740167,  0.76167574,  0.44500297, -0.82283116,  1.81169297,
       -0.28752125,  0.97017685,  0.73956995, -0.73630442,  0.08692948,
        0.13787149,  0.55253045,  0.06647032,  2.3039466 ,  0.847597  ,
       -1.24881181,  0.11960602, -0.28368008, -0.52099738,  0.53069813,
       -0.96316744,  0.62072585,  0.09391681, -0.92958286, -0.30584397])

In [29]:
randin100[0:4]

array([ 1.05081754,  1.25116587, -0.3078189 , -0.96681633])

In [31]:
list_randin = [0,50,99]
randin100[list_randin]

array([ 1.05081754,  1.0316474 , -0.30584397])

In [32]:
random_generator_seed =np.random.default_rng(234444)

In [33]:
low=0
high=10
size=(3,4)
two_d_array=random_generator_seed.uniform(low,high,size)
two_d_array

array([[6.31642888, 8.88428445, 2.32222016, 8.29015815],
       [6.2049529 , 4.45305267, 3.98661712, 6.51275693],
       [4.02671536, 5.7290404 , 9.1184929 , 4.18738454]])

In [38]:
two_d_array[1,:]

array([6.2049529 , 4.45305267, 3.98661712, 6.51275693])

In [39]:
two_d_array[1:2,:]

array([[6.2049529 , 4.45305267, 3.98661712, 6.51275693]])

In [40]:
mask_5 = two_d_array > 5 
mask_5

array([[ True,  True, False,  True],
       [ True, False, False,  True],
       [False,  True,  True, False]])

In [41]:
two_d_array[mask_5]

array([6.31642888, 8.88428445, 8.29015815, 6.2049529 , 6.51275693,
       5.7290404 , 9.1184929 ])