// NP ARRAYS

Numpy (ND arrrays) N- dimensional functions to develop calculations and mathematical operations with arrays in an efficient manner. (vectorization)
Operations of linear algebra , generation of random numbers amongst other fonctionalities of scientific computation.

In [2]:
import numpy as np

In [3]:
python_list= [1,2,3,4,5,6,7]
array=np.array(python_list)
print(array)

[1 2 3 4 5 6 7]


In [4]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros((10,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
np.ones((10,2),int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])