// NP ARRAYS

Numpy (ND arrrays) N- dimensional functions to develop calculations and mathematical operations with arrays in an efficient manner. (vectorization)
Operations of linear algebra , generation of random numbers amongst other fonctionalities of scientific computation.

In [2]:
import numpy as np

In [3]:
python_list= [1,2,3,4,5,6,7]
array=np.array(python_list)
print(array)

[1 2 3 4 5 6 7]


In [4]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros((10,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
np.ones((10,2),int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [11]:
random_generator=np.random.default_rng()

In [12]:
print(random_generator)

Generator(PCG64)


In [ ]:
random_generator.normal()


-0.7324403944189068

In [14]:
random_generator.normal(loc=0,scale=1,size=12)

array([ 1.55801328,  0.23978783,  0.93030481, -0.71811055, -0.80713832,
        0.09656822,  0.05240114,  0.19419458, -0.57572111,  0.49003974,
        0.88012294,  0.76621937])

In [15]:
random_generator.normal(loc=0,scale=1,size=100)

array([-1.33111394,  0.02966523,  0.22331481,  0.55461636, -0.06057773,
        0.62889133, -0.49161368,  0.17186932, -2.15120964, -1.29447184,
       -2.54682126, -0.16806183,  0.44931263,  1.2240907 ,  1.07979708,
       -1.28995444, -0.11822475, -0.06510769, -0.28794181, -0.68110134,
       -1.49827932,  0.2383748 ,  0.56837028, -2.19764784, -1.52739472,
        0.79888169, -1.09594221, -0.42125919, -0.21726542,  0.67527712,
        0.29150625,  0.8049963 , -0.66382449, -2.18010393,  1.61371926,
        0.32579606,  1.69552659, -0.10655099, -0.37512745, -0.06259292,
        2.21857826, -0.53290411, -0.15365799, -1.34739112,  0.4642633 ,
        1.49934763, -0.16323243,  0.1053978 , -0.90544127, -1.85078273,
       -2.14154327, -1.18885199,  1.15498642,  0.15048179,  1.17349262,
       -0.64383553, -0.71075818,  0.40464436,  1.46837708, -0.86995723,
       -1.25243014, -0.2069796 ,  0.17562661, -0.22107778, -0.2254469 ,
       -0.72723078, -0.51192385, -0.11423599, -0.33350582,  0.83